version: '3.8'

volumes:
  postgres-data:
  cargo:
  rustup:


services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: bookworm # use bullseye on apple silicon
        CARGO_HOME: /usr/local/cargo
        RUSTUP_HOME: /usr/local/rustup
    env_file:
      - .env
    environment:
      - JAEGER_HOST=http://jaeger:4317/v1/traces
    command: sleep infinity
    network_mode: service:db
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../..:/workspace:cached
      - cargo:/usr/local/cargo
      - rustup:/usr/local/rustup
    deploy:
      resources:
        limits:
          memory: 25G
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PG_DATA=/var/lib/progresql/data
    volumes:
      - postgres-data:/var/lib/progresql/data
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 5778:5778
      - 16686:16686
